web-compile:
  # Compiles our SCSS into CSS
  sass:
    encoding: utf8
    files:
      src/scss/basic-ng-template.scss: basic_ng_template/theme/basic_ng_template/static/basic-ng-template.css
    format: compressed
  # Minifies our JS into a bundle
  js:
    encoding: utf8
    files:
      src/js/basic-ng-template.js: basic_ng_template/theme/basic_ng_template/static/basic-ng-template.js
    format: compressed
  continue_on_error: true
  exit_code: 2
  test_run: false
  verbose: false
  quiet: false
  git_add: false  # Prevent web-compile from committing the generated assets
